# Defines whether this scoreboard is enabled or not.
enabled: true
# Permission that is required to see this scoreboard.
permission: ''
# Using this, you can add additional checks that might be required to see this scoreboard.
check_script: ''
weight: 0
# This will only impact servers that run a version older than 1.13
# Possible modes are:
# - SCOREBOARD_MAX_32 => this mode will allow for scoreboards UP TO 32 characters
# - SCOREBOARD_MAX_48 => this mode will allow for scoreboards UP TO 48 characters, but can be buggy every other time when using fast animations
mode: 'SCOREBOARD_MAX_48'
# What should the MINIMUM interval of the scoreboard be (in MILLISECONDS)?
# Default is 50, which is the equivalent of one tick in minecraft.
# Lowest possible is 1 ms, if you go for 0 or lower, the scoreboard will be seen as a static scoreboard!
# Do note, the interval in the title & line frames are multiplications of this interval
# For example, if you enter interval 25 here, and interval 10 at title, the title will update very 250 seconds (25 * 10)
interval: 50
title:
  # This interval (in MILLISECONDS) will be multiplied by the scoreboard interval.
  # So if the scoreboard interval is 25, and this interval is 1, this frame will update every 25 milliseconds (40~ times a second)
  interval: 1
  # The frames of the title
  frames:
    - '&0&lHello World'
    - '&1&lHello World'
    - '&2&lHello World'
    - '&3&lHello World'
    - '&4&lHello World'
    - '&5&lHello World'
    - '&6&lHello World'
    - '&7&lHello World'
    - '&8&lHello World'
    - '&9&lHello World'
    - '&a&lHello World'
    - '&b&lHello World'
    - '&c&lHello World'
    - '&d&lHello World'
    - '&e&lHello World'
    - '&f&lHello World'
lines:
  # This interval (in MILLISECONDS) will be multiplied by the scoreboard interval.
  # So if the scoreboard interval is 25, and this interval is 1, this frame will update every 25 milliseconds (40~ times a second)
  - interval: 1
    # The frames of the line
    frames:
      - '&6Hello World'
      - '&eH&6ello World'
      - '&eHe&6llo World'
      - '&eHel&6lo World'
      - '&eHell&6o World'
      - '&eHello &6World'
      - '&eHello W&6orld'
      - '&eHello Wo&6rld'
      - '&eHello Wor&6ld'
      - '&eHello Worl&6d'
      - '&eHello World'
      - '&eHello World'
      - '&eHello World'
      - '&eHello Worl&6d'
      - '&eHello Wor&6ld'
      - '&eHello Wo&6rld'
      - '&eHello W&6orld'
      - '&eHello &6World'
      - '&eHell&6o World'
      - '&eHel&6lo World'
      - '&eHe&6llo World'
      - '&eH&6ello World'
      - '&6Hello World'
      - '&6Hello World'
      - '&6Hello World'
  # This interval (in MILLISECONDS) will be multiplied by the scoreboard interval.
  # So if the scoreboard interval is 25, and this interval is 1, this frame will update every 25 milliseconds (40~ times a second)
  - interval: 1
    # The frames of the line
    frames:
      - '&2Hello World'
      - '&aH&2ello World'
      - '&aHe&2llo World'
      - '&aHel&2lo World'
      - '&aHell&2o World'
      - '&aHello &2World'
      - '&aHello W&2orld'
      - '&aHello Wo&2rld'
      - '&aHello Wor&2ld'
      - '&aHello Worl&2d'
      - '&aHello World'
      - '&aHello World'
      - '&aHello World'
      - '&aHello Worl&2d'
      - '&aHello Wor&2ld'
      - '&aHello Wo&2rld'
      - '&aHello W&2orld'
      - '&aHello &2World'
      - '&aHell&2o World'
      - '&aHel&2lo World'
      - '&aHe&2llo World'
      - '&aH&2ello World'
      - '&2Hello World'
      - '&2Hello World'
      - '&2Hello World'
  # This interval (in MILLISECONDS) will be multiplied by the scoreboard interval.
  # So if the scoreboard interval is 25, and this interval is 1, this frame will update every 25 milliseconds (40~ times a second)
  - interval: 1
    # The frames of the line
    frames:
      - '&4Hello World'
      - '&cH&4ello World'
      - '&cHe&4llo World'
      - '&cHel&4lo World'
      - '&cHell&4o World'
      - '&cHello &4World'
      - '&cHello W&4orld'
      - '&cHello Wo&4rld'
      - '&cHello Wor&4ld'
      - '&cHello Worl&4d'
      - '&cHello World'
      - '&cHello World'
      - '&cHello World'
      - '&cHello Worl&4d'
      - '&cHello Wor&4ld'
      - '&cHello Wo&4rld'
      - '&cHello W&4orld'
      - '&cHello &4World'
      - '&cHell&4o World'
      - '&cHel&4lo World'
      - '&cHe&4llo World'
      - '&cH&4ello World'
      - '&4Hello World'
      - '&4Hello World'
      - '&4Hello World'
  # This interval (in MILLISECONDS) will be multiplied by the scoreboard interval.
  # So if the scoreboard interval is 25, and this interval is 1, this frame will update every 25 milliseconds (40~ times a second)
  - interval: 1
    # The frames of the line
    frames:
      - '&9Hello World'
      - '&bH&9ello World'
      - '&bHe&9llo World'
      - '&bHel&9lo World'
      - '&bHell&9o World'
      - '&bHello &9World'
      - '&bHello W&9orld'
      - '&bHello Wo&9rld'
      - '&bHello Wor&9ld'
      - '&bHello Worl&9d'
      - '&bHello World'
      - '&bHello World'
      - '&bHello World'
      - '&bHello Worl&9d'
      - '&bHello Wor&9ld'
      - '&bHello Wo&9rld'
      - '&bHello W&9orld'
      - '&bHello &9World'
      - '&bHell&9o World'
      - '&bHel&9lo World'
      - '&bHe&9llo World'
      - '&bH&9ello World'
      - '&9Hello World'
      - '&9Hello World'
      - '&9Hello World'
  # This interval (in MILLISECONDS) will be multiplied by the scoreboard interval.
  # So if the scoreboard interval is 25, and this interval is 1, this frame will update every 25 milliseconds (40~ times a second)
  - interval: 1
    # The frames of the line
    frames:
      - '&5Hello World'
      - '&dH&5ello World'
      - '&dHe&5llo World'
      - '&dHel&5lo World'
      - '&dHell&5o World'
      - '&dHello &5World'
      - '&dHello W&5orld'
      - '&dHello Wo&5rld'
      - '&dHello Wor&5ld'
      - '&dHello Worl&5d'
      - '&dHello World'
      - '&dHello World'
      - '&dHello World'
      - '&dHello Worl&5d'
      - '&dHello Wor&5ld'
      - '&dHello Wo&5rld'
      - '&dHello W&5orld'
      - '&dHello &5World'
      - '&dHell&5o World'
      - '&dHel&5lo World'
      - '&dHe&5llo World'
      - '&dH&5ello World'
      - '&5Hello World'
      - '&5Hello World'
      - '&5Hello World'
  # This interval (in MILLISECONDS) will be multiplied by the scoreboard interval.
  # So if the scoreboard interval is 25, and this interval is 1, this frame will update every 25 milliseconds (40~ times a second)
  - interval: 1
    frames:
      - '<scroller spaces="15" max-width="40">&6Thank you for using &4HeroicScoreboard! &eNeed help or do you have a suggestion? &aDon''t hesitate to join our Discord at &2https://discord.dbsoftwares.eu&a!</scroller>'
  # This interval (in MILLISECONDS) will be multiplied by the scoreboard interval.
  # So if the scoreboard interval is 25, and this interval is 1, this frame will update every 25 milliseconds (40~ times a second)
  - interval: -1
    frames:
      - '&6&l&o'
  # This interval (in MILLISECONDS) will be multiplied by the scoreboard interval.
  # So if the scoreboard interval is 25, and this interval is 1, this frame will update every 25 milliseconds (40~ times a second)
  - interval: -1
    frames:
      - '&7Check out our Website: &adbsoftwares.eu !!'